### ISSUE TITLE
Difference vs. Autoware

### ISSUE THREAD

**Issue by ubicray** [project-aslan/Aslan#1]
First of all, I'd like to thank you guys for great work. Documentation is already better than what we can find in Autoware

One thing that I fail to see is the changes made to the packages taken from autoware

I'm considering using some parts of Aslan in the autoware project I'm working with, but it isn't easy without knowing what changes have been made

Best Regards

**Comment by HEGALLIS** [comment]
because they deliberately removed the change history - this is not open source, by forking someone else's work and claiming to be a new open source project...

**Comment by tekrajchhetri** [comment]
They did mentioned that it is modified from autoware already in their information.
"Originally suggested at Autoware 1.10.0.
These packages have been configured and modified significantly to fit the requirements of Project ASLAN."

**Comment by HEGALLIS** [comment]
@tekrajchhetri yes, and usually when such fork is done, people keep the change history - can you find the change history here? By keeping a line as "originally suggested in Autoware" is simply misleading. Majority of the code is copy-paste.

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Hi @ubicray ! Thanks for the feedback.  

To answer your question, we just included a complete Changelog of any alterations made to source code originating from open source projects. In total there are 40 packages in the Aslan GitHub, from which 23 originated from various open source projects, 11 were based in Autoware 1.10.0 and 6 were built specifically for Project Aslan.

You can find it here: [https://github.com/project-aslan/Aslan/blob/master/CHANGELOG.md](https://github.com/project-aslan/Aslan/blob/master/CHANGELOG.md)
Hope this helps! If you find anything missing, please let us know, else I will close this issue.

Have a great weekend!
