### ISSUE TITLE
Vector Maps

### ISSUE THREAD

**Issue by tekrajchhetri** [project-aslan/Aslan#10]
Hi,

Since the work is based on Autoware and it makes use of vector maps for additional information like cross walk, stop lines. However, I see no such information about vector maps in Aslan. Is there any reasons to not include it in project Aslan? Had it not been more beneficial to have vector maps?

Thank you.

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Hi @tekrajchhetri ,
This release of Aslan is tested and proven stable with point cloud maps only. On the latest [Changelog](https://github.com/project-aslan/Aslan/blob/master/CHANGELOG.md) you can find all the features in the aslan stack as well as the features added on other open source stacks and the differences between the original ones.

If you would like to add a new feature in Aslan please create a new feature request and we can discuss the specifics there.

**Comment by tekrajchhetri** [comment]
@EfimiaPanagiotaki-StreetDrone I checked the change log, could not find there, will create a feature request.
