### ISSUE TITLE
[Feature Request] Update for Ros Melodic and Ubuntu 18 

### ISSUE THREAD

**Issue by FionanOSullivan-StreetDrone** [project-aslan/Aslan#12]
**Which module?**
This feature request impacts all Modules. 

**Is it a solution suggestion to a problem?**
No

**Describe the feature you would like to implement**
This feature is to update Aslan to ROS Melodic and Ubuntu 18

**Describe alternatives you've considered**
Alternatively, development could remain Kinetic only, however this restricts the community to Ubuntu 16. 
ROS Noetic is also an option, however many sensor driver nodes are not yet available for ROS Noetic. 

**Additional context**

**Comment by tekrajchhetri** [comment]
Is it not good to move to ROS Noetic?

**Comment by cnkuyan** [comment]
Hi Fionan;

 Is this feature request and Bug#14 are related ?
thanks

**Comment by ParthAD3** [comment]
ok so now aslan will work on ros melodic ubuntu 18??

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
@ParthAD3 
The melodic version of Aslan is at the [melodic branch](https://github.com/project-aslan/Aslan/tree/melodic)
