### ISSUE TITLE
[BUG] Ouster Driver launched from GUI throws up error

### ISSUE THREAD

**Issue by FionanOSullivan-StreetDrone** [project-aslan/Aslan#13]
**Describe the bug**
The Ouster button from the GUI does not successfully launch the Ouster driver. 

This is because the parameter os1_hostname is not correctly specified in the launch file for the ouster hardware. 
This hostname is unique for every sensor. Potentially, extending the GUI to include a config to a hollow the hostname to specified shall rectify this issue. 

A workaround, would be to set a default hostname within the launch file. However this needs to be tested and documented. 

**Steps to reproduce**

**Expected behavior**
On launch, the driver is expected to output points_raw from the Ouster hardware

**Screenshots**

**Sytem (please complete the following information):**
 - OS: Ubuntu 16.04
 - ASLAN Version: 1.0.0
 - ROS Version: kinetic
 - Source Code

**Additional context**

**Comment by parth3153** [comment]
Ry

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Please advise the [Ouster ROS Driver's READMEs](https://github.com/ouster-lidar/ouster_example), the Ouster user manual and the [Ouster Issue tracker](https://github.com/ouster-lidar/ouster_example/issues) to solve any connectivity and networking issues.
