### ISSUE TITLE
[BUG] Failed to start Aslan using Docker run.bash

### ISSUE THREAD

**Issue by P4nos** [project-aslan/Aslan#14]
**Describe the bug**
When trying to execute the run.bash script from inside a locally built Docker container, Aslan fails to start.

**Steps to reproduce**
1. Execute the build.bash under the aslan_docker directory
2. Execute the run.bash under the aslan_docker directory
3. While inside the container run `./Aslan/run`

**Expected behavior**
Expected Aslan to run

**Screenshots**
This is what I see.
![Screenshot from 2020-07-21 22-13-20](https://user-images.githubusercontent.com/11441238/88104215-68b42b80-cba2-11ea-9281-873148184379.png)

**System (please complete the following information):**
 - Ubuntu 18.04
 - ASLAN Version 1.0.0
 - ROS Version: Melodic
 - Docker

**Additional context**

[comment]: # (In the case of urgent feedback needed, assign this issue to yourself and one of the core developers:)
[comment]: # (EfimiaPanagiotaki-StreetDrone)
[comment]: # (AbdelrahmanBarghouth-StreetDrone)
[comment]: # (FionanOSullivan-StreetDrone)

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
@P4nos the ROS Melodic release of Aslan for Ubuntu 18.04 will be best suited for your system.

The `run.bash` script is pulling the docker image from the [Dockerhub](https://hub.docker.com/repository/docker/projaslan/aslan) so when you run the script it will start the image [projaslan/aslan](https://hub.docker.com/repository/registry-1.docker.io/projaslan/aslan/tags?page=1). The script `build.bash` is building the image aslan_docker, locally which will most likely be broken if it was built with Aslan 1.1.0, on top of an Ubuntu 18.04 OS. The Aslan GUI won't launch if the built of the catkin workspace was not finished properly. Did you get any errors when building the docker with ./build.bash, on the step `catkin build` of Aslan?

For now, try only executing the `run.bash` script which launches an instance of Ubuntu 16.04 and ROS Kinetic and use Aslan from there.

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
@P4nos 
The ROS Melodic release of Aslan is at the [melodic branch](https://github.com/project-aslan/Aslan/tree/melodic) and the melodic docker is at [projaslan/aslan:melodic](https://hub.docker.com/r/projaslan/aslan/tags)
You should now be able to use Aslan however you like (docker or source)

If you run the melodic docker , are you still getting the same error?
For reference, to launch the melodic docker:
```
cd Aslan/
git checkout melodic
cd aslan_docker/
./run.bash 
```
