### ISSUE TITLE
Lidar is not launching in the Gazebo simulation[BUG]

### ISSUE THREAD

**Issue by thiagodeborba** [project-aslan/Aslan#24]
**Describe the bug*
I am trying to go through the tutorial. However, the Lidar is not launching with the simulation.
I can neither see the points in RViz nor record a rosbag to generate the trajectory.
How can I solve it?

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
The lidar driver is being launched automatically when clicking on the SD Twizy model button. The driver used is the integrated VLP-16 driver that can be found [here](https://github.com/project-aslan/Aslan/tree/master/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_description/urdf/sensors).
To only visualize the lidar points, on rviz go to Displays -> Global Options -> Fixed_Frame and change it to base_link or velodyne.   

The default rviz file is pointing by default to map frame which on the step that you are at is not there.

**Comment by thiagodeborba** [comment]
Now I can see the vehicle in red, but no lines regarding the LIDAR reflections.

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Please make sure you have completed the following steps when installing Project Aslan, as described [here](https://github.com/project-aslan/Aslan#3-clone-the-project-aslan-repository-with-submodules):
```
cd Aslan/
git submodule update --init --recursive
rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
```

If this didn't fix your issue, make sure that the [velodyne_gazebo_plugin](http://wiki.ros.org/velodyne_gazebo_plugins) is installed. To install it, do `sudo apt-get install ros-melodic-velodyne-gazebo-plugins` for melodic or `sudo apt-get install ros-kinetic-velodyne-gazebo-plugins` for kinetic.

**Comment by thiagodeborba** [comment]
I still can't see the LIDAR reflections and now there are 2 errors, 1 regarding Point Map and the other is regarding Points Raw.

**Comment by thiagodeborba** [comment]
I used both commands again, catkin init and catkin_make, now I can see the reflections.
Thank you so much!

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Awesome :) :+1:
