### ISSUE TITLE
[BUG] Map and reflected points do not match

### ISSUE THREAD

**Issue by thiagodeborba** [project-aslan/Aslan#28]
After generating the Map using the lidar point cloud. The Map and the reflected Lidar points do not match, they are shifted, in Rviz.
![grafik](https://user-images.githubusercontent.com/73481007/97959242-3922db00-1daf-11eb-9861-61c9e0586325.png)

**Comment by AbdelrahmanBarghouth-StreetDrone** [comment]
Hi Thiago
There is a tool in Rviz in the tool bar at the top of the window, called "2D Pose Estimate". Try to zoom in in your point cloud as much as You can and then use this tool to drag an arrow from the position that you expect the car should be and the direction of arrow is the expected direction of your car.
This is a manual pose estimation that is needed to be done if the automatic pose estimation which expects car to be at position (0, 0, 0) in the map.
Please let us know if this solves your issue

Please try to use the template of the issues as it helps us so much answers your questions. We are delighted in your interest in Aslan and waiting for more issues you discover and hopefully a contribution in the near future :+1:
