### ISSUE TITLE
[BUG] Waypoints

### ISSUE THREAD

**Issue by thiagodeborba** [project-aslan/Aslan#29]
After creating the Waypoints, I notice they have a completely different trajectory when compared to the one I used to create these Waypoints.
And sometimes the waypoints saver saves just the first point as shown in the files attached.
[Tutorial6.zip](https://github.com/project-aslan/Aslan/files/5479894/Tutorial6.zip)

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Please consult the tutorials [found here](https://www.youtube.com/watch?v=NMTgGqwPdac&t=9s&ab_channel=ProjectAslan). If you find an error on these tutorials, please write it in the comments.

Make sure to monitor localization when running the software and extracting the waypoints. When extracting the waypoints, open rviz and click on Add-> By topic and select the MarkerArray to visualize the waypoints you are extracting
