### ISSUE TITLE
[BUG] Missing model.config

### ISSUE THREAD

**Issue by mustafakurban** [project-aslan/Aslan#31]
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/.gazebo/models/meshes"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/.gazebo/models/sd_description"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/.gazebo/models/sd_docs"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/Aslan/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_description/meshes"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/Aslan/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_description/urdf"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/opt/ros/kinetic/share/turtlebot3_gazebo/models/turtlebot3_autorace"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/Aslan/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_control/../sd_control"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/Aslan/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_control/../sd_description"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/Aslan/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_control/../sd_docs"
[Err] [InsertModelWidget.cc:302] Missing model.config for model "/home/mustafa/Aslan/src/vehicle_simulation/gazebo/sd_twizy_model/streetdrone_model/sd_control/../sd_robot"

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
This is known in Gazebo. That error can just be considered a warning, so you can ignore it. It doesn't affect the functionality of the stack.

**Comment by sqn175** [comment]
Hi, 
I ran the docker and occured the same problem.
![Screenshot from 2020-11-05 11-02-45](https://user-images.githubusercontent.com/10163611/98192734-88574000-1f56-11eb-9caa-a16300b74baa.png)

And the Gazebo stuck in "Preparing your world ..." as follows:
![Screenshot from 2020-11-05 11-04-19](https://user-images.githubusercontent.com/10163611/98192798-ab81ef80-1f56-11eb-8160-9f66d6d2bf71.png)

What's the solution to this stuck problem? This actually affects the functionality of the stack. 

Thanks!

**Comment by AbdelrahmanBarghouth-StreetDrone** [comment]
Hi Mustafa,
Can You tell us which world are you trying to load??
On the docker gazebo takes about 10-13 mins to open. It is a known issue in docker and ROS when using graphics on docker

**Comment by mustafakurban** [comment]
I'll wait 12 13 minutes as you said on next try.
also gives the same error in all worlds

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Hi @mustafakurban , 
As mentioned above this error is known in Gazebo and can just be considered a warning, so you can ignore it. It doesn't affect the functionality of the stack.
You can find more details [here](https://github.com/ros-ukraine/leobot/issues/143) and [here](https://github.com/KumarRobotics/mrsl_quadrotor/issues/4)
The error won't go away, but it's also not an issue.

Hi @sqn175, 
If you are trying to run Gazebo from the docker, it will take some time to load. The missing model.config error won't go away.
If you still have issues with Gazebo and rviz when running the docker, make sure you have installed the nvidia drivers that are suitable for your machine and that nvidia-docker is installed properly in your machine.
