### ISSUE TITLE
[SDD] What radar antenna parameters can be configed

### ISSUE THREAD

**Issue by DanielTian90** [project-aslan/Aslan#34]
Is it possible to test radar antenna paramter(antena tx rx layout, gain etc.) with this tool?

**Comment by AbdelrahmanBarghouth-StreetDrone** [comment]
Hi @DanielTian90 
Which radar are You using??
Aslan has GUI where You can't configure radar parameters there but You can add source code of the driver of the radar You are using and edit the configuration in this driver

**Comment by DanielTian90** [comment]
77GHz radar, similar to Conti ARS-508

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Hi Daniel,

Aslan does not support this. It's best to advise the documentation provided by your supplier, for the radar you are using.
