### ISSUE TITLE
[BUG] When running a simulation the sd_vehicle_interface node doesn't launch 

### ISSUE THREAD

**Issue by mdempse1** [project-aslan/Aslan#35]
We have developed an interface to an rFpro simulator that subcribes and publishes ROS topics directly.  When we click GO on the Aslan UI the vehicle doesn't start to drive because the sd_vehicle_interface node does not launch correctly.  When we manually launch this node using roslaunch the vehicle starts driving correctly.

The bug is that the sd_vehicle_interface doesn't start automatically and we believe it's supposed to.

We can launch the node manually and the vehicle starts to drive correctly using the following command

roslaunch sd_vehicle_interface sd_vehicle_interface.launch sd_vehicle:=twizy sd_gps_imu:=none sp_speed_source:=ndt_speed sd_simulation_mode:=true

We're running Aslan on Ubuntu 16.04.

**Comment by AbdelrahmanBarghouth-StreetDrone** [comment]
Hi @mdempse1 
Please use this command when running 
rosparam set /use_sim_time true
