### ISSUE TITLE
Unable to start gazebo

### ISSUE THREAD

**Issue by QianLu666** [project-aslan/Aslan#36]
Hi

After installing ASLAN, i pressed 'SD Twizy model' to start the simulation. Gazebo doesn't come up and i get the errors captured in the following images. Could you please help me to resolve the issue? Thanks
![Gazeboerror1](https://user-images.githubusercontent.com/83706902/118135388-e0399c80-b3fa-11eb-8f08-22f26d2d875e.png)
![Gazeboerror2](https://user-images.githubusercontent.com/83706902/118135392-e0399c80-b3fa-11eb-9a72-e13e5363f229.png)
![Gazeboerror3](https://user-images.githubusercontent.com/83706902/118135393-e0d23300-b3fa-11eb-827d-3bd8d77b8e87.png)
![Gazeboerror4](https://user-images.githubusercontent.com/83706902/118135394-e0d23300-b3fa-11eb-9897-dd3876ab3afe.png)

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Hi Qian,

Please have a look at the vehicle_model package readme [here](https://github.com/project-aslan/Aslan/tree/master/src/vehicle_simulation/gazebo/sd_twizy_model). You are working with Gazebo 7.0 but this model has been tested and is working with Gazebo 7.16.0 for Ubuntu 16.04 and ROS Kinetic. Run `gazebo --version` to make sure you have the correct version installed.
To update to Gazebo 7.16.0, do:  

```
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
sudo apt update && sudo apt upgrade
```
