### ISSUE TITLE
Vehicle Interface ROS Melodic

### ISSUE THREAD

**Issue by thiagodeborba** [project-aslan/Aslan#38]
I am facing some problems with the vehicle interface. Could you please give me some help with this?
 
How to reproduce the problem:
Launch Aslan Melodic version, than I go to control tab and I select SD Vehicle Twizy, Speed Input Localization, GPS/IMU None, Mode Vehicle.
Then I enable the Linux CAN Driver, also entering the sudo password.
Then I press GO.
 
Or
 
I created a catkin_WS with Vehicle Interface and msgs folder.
Then catkin_make --only-pkg-with-deps sd_vehicle_interface 
sudo modprobe peak_usb
sudo ip link set can0 up type can bitrate 500000
roslaunch sd_vehicle_interface sd_vehicle_interface.launch sd_vehicle:=twizy sd_gps_imu:=peak
 
Behaviour observed: With the drive by wire on, the red light stop blinking when the vehicle interface is on. Once I turn the black switch to the right, the yellow light starts blinking and after some seconds the system makes an error sound and both green and yellow lights start toggling. 
Repeating this process for many times, the full communication can be achieved. But it is too time consuming. But it I restart the system, again I need to repeat the same procedure many times to achieve full communication again.
 
 
Could you please test the Vehicle Interface Melodic Version and provide me a feedback? 
 
Also when I launch the vehicle interface with sd_gps_imu:=peak option the following error message pops up:
SD_Vehicle_Interface parameter for sd_gps_imu is not valid.
 
How can I solve this?

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Thanks for logging this. We are planning to include the solution on the next release. In the meantime, if you are using the melodic branch, please replace the sd_vehicle_interface package in Aslan with the one [in this commit](https://github.com/project-aslan/Aslan/tree/79cf96c204f299a8eb4eefa35f9a25c185ae225d/src/vehicle_interface/sd_vehicle_interface)

**Comment by thiagodeborba** [comment]
Hello Efimia,

After some tries I could establish full communication. But the brake pedal starts vibrating a lot and making a lot of noise.

Additionally,  the error : SD_Vehilce_interface parameter for sd_gps_imu is not valid still appears.

Could you help me with this?

Best regards,
Thiago


--------------------------------------------------------+i

Technische Hochschule Ingolstadt

Thiago de Borba
Abteilung C-ISAFE

Esplanade 10, D-85049 Ingolstadt
Tel +49 841 9348-5058
***@***.******@***.***>

www.thi.de<http://www.thi.de>
Von: EfimiaPanagiotaki-StreetDrone ***@***.***>
Gesendet: Montag, 5. Juli 2021 13:30
An: project-aslan/Aslan ***@***.***>
Cc: de Borba, Thiago ***@***.***>; Author ***@***.***>
Betreff: Re: [project-aslan/Aslan] Vehicle Interface ROS Melodic (#38)


Thanks for logging this. We are planning to include the solution on the next release. In the meantime, if you are using the melodic branch, please replace the sd_vehicle_interface package in Aslan with the one in this commit<https://github.com/project-aslan/Aslan/tree/79cf96c204f299a8eb4eefa35f9a25c185ae225d/src/vehicle_interface/sd_vehicle_interface>

**Comment by thiagodeborba** [comment]
Hi Efimia,

The Vehicle interface behavior for Melodic is still too unstable.
After trying to establish the connection for more than 15 times we are able to establish connection. If we reboot the system, we again need more than 15 tries to establish connection.
Could you please take a look on it?

Additionally ,I am getting an error message when I choose peak as sd_gps_imu:=peak.
Do you know how can I solve this?

Best regards,
Thiago

--------------------------------------------------------+i

Technische Hochschule Ingolstadt

Thiago de Borba
Abteilung C-ISAFE

Esplanade 10, D-85049 Ingolstadt
Tel +49 841 9348-5058
***@***.******@***.***>

www.thi.de<http://www.thi.de>
Von: EfimiaPanagiotaki-StreetDrone ***@***.***>
Gesendet: Montag, 5. Juli 2021 13:30
An: project-aslan/Aslan ***@***.***>
Cc: de Borba, Thiago ***@***.***>; Author ***@***.***>
Betreff: Re: [project-aslan/Aslan] Vehicle Interface ROS Melodic (#38)


Thanks for logging this. We are planning to include the solution on the next release. In the meantime, if you are using the melodic branch, please replace the sd_vehicle_interface package in Aslan with the one in this commit<https://github.com/project-aslan/Aslan/tree/79cf96c204f299a8eb4eefa35f9a25c185ae225d/src/vehicle_interface/sd_vehicle_interface>

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
Hi Thiago,

Please make sure you are following the instructions in your vehicle's manual that specify how you should connect to the vehicle's drive by wire system and make sure you are following the tutorials and readmes in Project Aslan. Please confirm the following:
1. Are there obstacles in front of the vehicle?
2. Is sd_control topic being published
3. What speed value you are sending?

These seem like customer-specific and vehicle-related questions so it's best to log a ticket on Zendesk. If additional support is needed, the engineers will take it from there.

**Comment by EfimiaPanagiotaki-StreetDrone** [comment]
For your second question about the sd_gps_imu. Just found a bug in [line 94 of the sd_vehicle_interface.cpp](https://github.com/project-aslan/Aslan/blob/79cf96c204f299a8eb4eefa35f9a25c185ae225d/src/vehicle_interface/sd_vehicle_interface/src/sd_vehicle_interface/sd_vehicle_interface.cpp#L94)
I will include the fix in the next release - thanks for pointing it out. For now, please change this line to: `private_nh.param<string>("sd_gps_imu", _sd_gps_imu, "oxts");`
Let me know how this goes

**Comment by thiagodeborba** [comment]
> Hi Thiago,
> 
> Please make sure you are following the instructions in your vehicle's manual that specify how you should connect to the vehicle's drive by wire system and make sure you are following the tutorials and readmes in Project Aslan. Please confirm the following:
> 
> 1. Are there obstacles in front of the vehicle?
> 2. Is sd_control topic being published
> 3. What speed value you are sending?
> 
> These seem like customer-specific and vehicle-related questions so it's best to log a ticket on Zendesk. If additional support is needed, the engineers will take it from there.

Hello @EfimiaPanagiotaki-StreetDrone 
Yes, I am fully aware of the handshake procedure to enter autonomous mode.
I am launching only the vehicle interface. In order to establish communication, it is necessary to run the interface many times +15 times. Could you please try to run the Vehicle interface ( Melodic version ) in one car of yours? This is the only way for you to understand the issues we are facing.


Thank you!

**Comment by thiagodeborba** [comment]
> For your second question about the sd_gps_imu. Just found a bug in [line 94 of the sd_vehicle_interface.cpp](https://github.com/project-aslan/Aslan/blob/79cf96c204f299a8eb4eefa35f9a25c185ae225d/src/vehicle_interface/sd_vehicle_interface/src/sd_vehicle_interface/sd_vehicle_interface.cpp#L94)
> I will include the fix in the next release - thanks for pointing it out. For now, please change this line to: `private_nh.param<string>("sd_gps_imu", _sd_gps_imu, "oxts");`
> Let me know how this goes

Hello @EfimiaPanagiotaki-StreetDrone 
The error despairs. Thank you!
The imu topic is being published correctly.
But the GPS topic publish no data regarding longitude and latitude. ( the car was in open air area).
Could you take a look on it ? ( Melodic version)

**Comment by thiagodeborba** [comment]
Hello @EfimiaPanagiotaki-StreetDrone 

When will be the next release of the Vehicle Interface for ROS Melodic?
