### ISSUE TITLE
[BUG] ./run: line 23: --geometry=50x10+0+0: command not found

### ISSUE THREAD

**Issue by logicraju** [project-aslan/Aslan#43]
**Describe the bug**
./run: line 23: --geometry=50x10+0+0: command not found

**Steps to reproduce**
1. Go to 'Aslan' root folder
2. Open terminal and type ./run
3. See error: "./run: line 23: --geometry=50x10+0+0: command not found"

**Expected behavior**
Aslan not loading

**Screenshots**
https://drive.google.com/file/d/1_o9ovh2cNbE-Ry801aaVLcZsn9apDuAH/view?usp=sharing

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - ASLAN Version: 1.0.0
 - ROS Version: Melodic

**Comment by SanderVanDijk-StreetDrone** [comment]
Hi @logicraju, this looks like `gnome-terminal` is not installed. You can check by running `dpkg -l gnome-terminal`. Is this on a headless system maybe, or is this standard Ubuntu desktop?

**Comment by logicraju** [comment]
Hi @SanderVanDijk-StreetDrone,

Thanks for the reply. Yes, you're right. Installing gnome-terminal seems to have fixed the issue:

sudo apt install gnome-terminal

It is a standard Ubuntu Desktop

Regards

**Comment by SanderVanDijk-StreetDrone** [comment]
Great, interesting it wasn't there. I have a change coming that will remove the requirement to have gnome-terminal there, I will leave this open until I get that in.

**Comment by logicraju** [comment]
That sounds great !
